### ISSUE TITLE
Support for public GDrive links?

### ISSUE THREAD

**Issue by pedro380085** [pch-innovations/gdrive-finder-service#5]
Hi,

Would it be possible to add support to convert public links, such as https://drive.google.com/drive/u/0/folders/xxxxxxxxxxxxxxx to internal files on Finder?

**Comment by dotKokott** [comment]
That would be an interesting feature! How do you imagine the interaction?

You receive a public link from someone. How would we go about converting this link?

I suppose we could add this also to the services when right clicking a link and add a context menu item that says "Copy as internal path"

The challenge with this is that we would unfortunately have to add authentication to the app. Because in order to convert a gdrive GUID to the actual folder it is pointing to we would need to login with your specific google account.

**Comment by pedro380085** [comment]
Nice, I am glad that you like the idea!

Well, in order to avoid the authentication on the app, I was thinking about a Google Chrome extension. When you'd receive a public link, you would click on it and open it on the browser. Then the Chrome extension could capture the path using maybe an HTML scrapper from the bar (?) and return the internal path to the user.

**Comment by dotKokott** [comment]
That would work if the url would actually contain the path to the folder. 

Unfortunately in google drive every folder just has a unique has a GUID. So the actual url when you are browsing google drive is something like
`https://drive.google.com/drive/u/1/folders/0APr8Cpq2K63GUk9PVB` instead of `https://drive.google.com/drive/u/1/folders/clients/my_client`

So just from the url we cannot infer the path. For that we would need to have user authentication and ask google to tell us which folder '0APr8Cpq2K63GUk9PVB' on our user account is and recreate the folder structure.

If there would be a way to use the users local google drive app to resolve the GUID `0APr8Cpq2K63GUk9PVB` to the local folder path that would be great. I do not know how to achieve that though.

**Comment by pedro380085** [comment]
Hi, I think that we can capture the path through a Chrome extenson. For example, when we click on the link `https://drive.google.com/drive/u/1/folders/0APr8Cpq2K63GUk9PVB` it would open the following page:


<img width="812" alt="Screenshot 2023-05-15 at 16 21 21" src="https://github.com/pch-innovations/gdrive-finder-service/assets/1212753/4db85579-ff17-487f-bcc8-6f9d678df7e4">

We could then use a Chrome extension to capture this path?

**Comment by pedro380085** [comment]
Actually Google Drive web just launched a super incredible feature — when you preview a file on the browser and have Google Drive app installed on your Mac, it shows a button (on the web browser) saying "open in" and these are apps installed on your Mac, such as VLC, Preview, etc. So this feature we were requesting here is now native!

I will close the thread. Thanks,
